language: node_js

node_js:
  - "7"
  
install: 
  - npm install
  
script:
  - npm test

notification: 
  email: 
    recipients:
      - kdzaldua@up.edu.ph
      - arpacada@up.edu.ph
      - mmmeguillo@up.edu.ph
    on_success: always
    on_failure: always
      
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 139b908d3f7752dc3938c4e7ed450252cc6039cb
  on:
    branch: development
